version: "3"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-app:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
