version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    
  node:
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
