version: "3"

services:
  app:
    image: node
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 1546:1546
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
