version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
    
  node:
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
